server:
  port: 8080

spring:
  application:
    name: as241s5-aej-09-be
  data:
    mongodb:
      database: as241s5_db
      uri: mongodb+srv://robertoespinozan_db_user:GitXhap123486@cluster0.pzbjttw.mongodb.net/?appName=Cluster0

rapidapi:
  key: 2c7f8b9dd0msh4e3eafe659dd865p147ecejsn9c1f3b9c32df

copilot:
  api:
    url: https://copilot5.p.rapidapi.com/copilot
    host: copilot5.p.rapidapi.com

gemini:
  api:
    url: https://gemini-pro-ai.p.rapidapi.com/
    host: gemini-pro-ai.p.rapidapi.com