apiVersion: v1
kind: Secret
metadata:
  name: roberto-espinoza-07-secret
  namespace: roberto-espinoza-07-namespace
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLWZhbmN5LW1vdXNlLWFuejBpYnpyLXBvb2xlci5jLTYudXMtZWFzdC0xLmF3cy5uZW9uLnRlY2gvbmVvbmRiP3NzbG1vZGU9cmVxdWlyZQ==
  DATABASE_USERNAME: bmVvbmRiX293bmVy
  DATABASE_PASSWORD: bnBnX2dRcG1CanU3R0kyVw==
  RAPIDAPI_KEY: MmM3ZjhiOWRkMG1zaDRlM2VhZmU2NTlkZDg2NXAxNDdlY2Vqc245YzFmM2I5YzMyZGY=
  COPILOT_API_URL: aHR0cHM6Ly9jb3BpbG90NS5wLnJhcGlkYXBpLmNvbS9jb3BpbG90
  COPILOT_API_HOST: Y29waWxvdDUucC5yYXBpZGFwaS5jb20=
  GEMINI_API_URL: aHR0cHM6Ly9nZW1pbmktcHJvLWFpLnAucmFwaWRhcGkuY29tLw==
  GEMINI_API_HOST: Z2VtaW5pLXByby1haS5wLnJhcGlkYXBpLmNvbQ==

# r2dbc:postgresql://ep-fancy-mouse-anz0ibzr-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require = cjJkYmM6cG9zdGdyZXNxbDovL2VwLWZhbmN5LW1vdXNlLWFuejBpYnpyLXBvb2xlci5jLTYudXMtZWFzdC0xLmF3cy5uZW9uLnRlY2gvbmVvbmRiP3NzbG1vZGU9cmVxdWlyZQ==

# neondb_owner = bmVvbmRiX293bmVy

# npg_gQpmBju7GI2W = bnBnX2dRcG1CanU3R0kyVw==
