name: Code Quality - Super-Linter

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
  workflow_dispatch:

permissions:
  contents: read
  statuses: write

jobs:
  super-linter:
    name: Run Super-Linter
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # 2. Ejecutar el súper validador automático
      - name: Run GitHub Super-Linter
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false 
          DEFAULT_BRANCH: test # <-- Cambiado a test para que haga el match correcto con tu rama de pruebas
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}